"""empty message

Revision ID: 3f51ab8cf87b
Revises: 
Create Date: 2021-12-02 18:17:12.824460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f51ab8cf87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idCategory')
    )
    op.create_table('location',
    sa.Column('idLocation', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idLocation')
    )
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('location_idlocation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_idlocation'], ['location.idLocation'], ),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('Advertisement',
    sa.Column('idAdvertisment', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=45), nullable=False),
    sa.Column('DataOfPublishing', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.Enum('open', 'close'), nullable=True),
    sa.Column('idLocation', sa.Integer(), nullable=True),
    sa.Column('idCategory', sa.Integer(), nullable=True),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCategory'], ['category.idCategory'], ),
    sa.ForeignKeyConstraint(['idLocation'], ['location.idLocation'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idUser'], ),
    sa.PrimaryKeyConstraint('idAdvertisment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Advertisement')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('category')
    # ### end Alembic commands ###
